name: truck_detection_env
channels:
  - plotly
  - anaconda
  - defaults
  - conda-forge
dependencies:
  - _r-mutex=1.0.0
  - affine=2.3.0
  - aiohttp=3.7.3
  - alabaster=0.7.12
  - altair=4.1.0
  - appdirs=1.4.4
  - argh=0.26.2
  - argon2-cffi=20.1.0
  - arrow=1.2.1
  - astroid=2.4.2
  - async-timeout=3.0.1
  - async_generator=1.10
  - atomicwrites=1.4.0
  - attrs=20.3.0
  - autopep8=1.5.6
  - babel=2.9.1
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.1
  - bcrypt=3.2.0
  - binaryornot=0.4.4
  - black=21.7b0
  - blas=1.0
  - bleach=3.2.1
  - blosc=1.20.1
  - boost-cpp=1.74.0
  - brotli=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2022.3.29
  - cachetools=4.1.1
  - certifi=2021.10.8
  - cffi=1.14.4
  - cfitsio=3.470
  - chardet=3.0.4
  - charls=2.1.0
  - click=7.1.2
  - click-plugins=1.1.1
  - cligj=0.7.1
  - cloudpickle=1.6.0
  - colorama=0.4.4
  - cookiecutter=1.7.3
  - cryptography=3.3.1
  - curl=7.71.1
  - cycler=0.10.0
  - cytoolz=0.11.0
  - dask-core=2020.12.0
  - dataclasses=0.8
  - decorator=4.4.2
  - defusedxml=0.6.0
  - diff-match-patch=20200713
  - earthengine-api=0.1.244
  - entrypoints=0.3
  - expat=2.2.9
  - fiona=1.8.18
  - flake8=3.8.4
  - freetype=2.10.4
  - freexl=1.0.5
  - future=0.18.2
  - gdal=3.1.4
  - geopandas=0.9.0
  - geos=3.8.1
  - geotiff=1.6.0
  - gettext=0.19.8.1
  - giflib=5.2.1
  - glib=2.66.3
  - google-api-core=1.22.2
  - google-api-python-client=1.12.8
  - google-auth=1.23.0
  - google-auth-httplib2=0.0.4
  - google-cloud-core=1.4.4
  - google-cloud-storage=1.19.0
  - google-crc32c=1.0.0
  - google-resumable-media=1.1.0
  - googleapis-common-protos=1.52.0
  - grpcio=1.34.0
  - hdf4=4.2.13
  - hdf5=1.10.6
  - httplib2=0.18.1
  - icc_rt=2019.0.0
  - icu=67.1
  - idna=2.10
  - imagecodecs=2020.5.30
  - imageio=2.9.0
  - imagesize=1.3.0
  - imbalanced-learn=0.8.0
  - importlib-metadata=3.1.1
  - importlib_metadata=3.1.1
  - inflection=0.5.1
  - intel-openmp=2020.3
  - intervaltree=3.0.2
  - ipykernel=5.4.2
  - ipython=7.18.1
  - ipython_genutils=0.2.0
  - isort=5.6.4
  - jedi=0.17.2
  - jinja2=2.11.2
  - jinja2-time=0.2.0
  - joblib=1.0.0
  - jpeg=9d
  - json5=0.9.5
  - jsonschema=3.2.0
  - jupyter_client=6.1.7
  - jupyter_core=4.7.0
  - jupyterlab=2.2.6
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=1.2.0
  - jupytext=1.13.8
  - jxrlib=1.1
  - kealib=1.4.14
  - keyring=22.3.0
  - kiwisolver=1.3.1
  - krb5=1.17.2
  - lazy-object-proxy=1.4.3
  - lcms2=2.11
  - lerc=2.2
  - libaec=1.0.4
  - libblas=3.8.0
  - libcblas=3.8.0
  - libclang=10.0.1
  - libcrc32c=1.1.1
  - libcurl=7.71.1
  - libffi=3.3
  - libgdal=3.1.4
  - libglib=2.66.3
  - libiconv=1.16
  - libkml=1.3.0
  - liblapack=3.8.0
  - libnetcdf=4.7.4
  - libpng=1.6.37
  - libpq=12.3
  - libprotobuf=3.14.0
  - libsodium=1.0.18
  - libspatialindex=1.9.3
  - libspatialite=5.0.0
  - libssh2=1.9.0
  - libtiff=4.1.0
  - libwebp-base=1.1.0
  - libxml2=2.9.10
  - libzopfli=1.0.3
  - lz4-c=1.9.2
  - m2w64-bwidget=1.9.10
  - m2w64-bzip2=1.0.6
  - m2w64-expat=2.1.1
  - m2w64-fftw=3.3.4
  - m2w64-flac=1.3.1
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gettext=0.19.7
  - m2w64-gmp=6.1.0
  - m2w64-gsl=2.1
  - m2w64-libiconv=1.14
  - m2w64-libjpeg-turbo=1.4.2
  - m2w64-libogg=1.3.2
  - m2w64-libpng=1.6.21
  - m2w64-libsndfile=1.0.26
  - m2w64-libtiff=4.0.6
  - m2w64-libvorbis=1.3.5
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - m2w64-libxml2=2.9.3
  - m2w64-mpfr=3.1.4
  - m2w64-openblas=0.2.19
  - m2w64-pcre=8.38
  - m2w64-speex=1.2rc2
  - m2w64-speexdsp=1.2rc3
  - m2w64-tcl=8.6.5
  - m2w64-tk=8.6.5
  - m2w64-tktable=2.10
  - m2w64-wineditline=2.101
  - m2w64-xz=5.2.2
  - m2w64-zlib=1.2.8
  - markdown-it-py=2.1.0
  - markupsafe=1.1.1
  - matplotlib=3.4.1
  - matplotlib-base=3.4.1
  - mccabe=0.6.1
  - mdit-py-plugins=0.3.0
  - mdurl=0.1.0
  - mistune=0.8.4
  - mkl=2020.4
  - mkl-service=2.3.0
  - msys2-conda-epoch=20160418
  - multidict=4.7.5
  - munch=2.5.0
  - mypy_extensions=0.4.3
  - nbclient=0.5.1
  - nbconvert=6.0.7
  - nbformat=5.0.8
  - nest-asyncio=1.4.3
  - networkx=2.5
  - notebook=6.1.4
  - numpy=1.19.4
  - numpydoc=1.1.0
  - olefile=0.46
  - openjpeg=2.3.1
  - openssl=1.1.1n
  - packaging=20.8
  - pandas=1.1.5
  - pandoc=2.11.2
  - pandocfilters=1.4.2
  - paramiko=2.8.0
  - parso=0.7.0
  - pathspec=0.9.0
  - patsy=0.5.1
  - pcre=8.44
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=8.0.1
  - pip=20.3.1
  - pixman=0.40.0
  - plotly=4.14.3
  - plotly_express=0.4.0
  - pluggy=1.0.0
  - poppler=0.89.0
  - poppler-data=0.4.10
  - postgresql=12.3
  - poyo=0.5.0
  - proj=7.1.1
  - prometheus_client=0.9.0
  - prompt-toolkit=3.0.8
  - protobuf=3.14.0
  - psutil=5.8.0
  - ptyprocess=0.7.0
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.7
  - pycodestyle=2.6.0
  - pycparser=2.20
  - pydocstyle=6.1.1
  - pyflakes=2.2.0
  - pygments=2.7.3
  - pylint=2.6.0
  - pyls-black=0.4.6
  - pyls-spyder=0.3.2
  - pynacl=1.4.0
  - pyopenssl=20.0.0
  - pyparsing=2.4.7
  - pyproj=2.6.1.post1
  - pyqt=5.12.3
  - pyqt-impl=5.12.3
  - pyqt5-sip=4.19.18
  - pyqtchart=5.12
  - pyqtwebengine=5.12.1
  - pyrsistent=0.17.3
  - pysocks=1.7.1
  - python=3.8.6
  - python-dateutil=2.8.1
  - python-jsonrpc-server=0.4.0
  - python-language-server=0.36.2
  - python-slugify=5.0.2
  - python_abi=3.8
  - pytz=2020.4
  - pywavelets=1.1.1
  - pywin32=228
  - pywin32-ctypes=0.2.0
  - pywinpty=0.5.7
  - pyyaml=5.3.1
  - pyzmq=20.0.0
  - qdarkstyle=3.0.2
  - qstylizer=0.2.1
  - qt=5.12.9
  - qtawesome=1.1.0
  - qtconsole=5.2.0
  - qtpy=1.11.2
  - r-base=3.6.1
  - r-tree=1.0_40
  - rasterio=1.2.1
  - regex=2021.11.10
  - requests=2.25.0
  - retrying=1.3.3
  - rope=0.21.1
  - rsa=4.6
  - rtree=0.9.4
  - scikit-image=0.17.2
  - scikit-learn=0.24.1
  - scipy=1.5.2
  - seaborn=0.11.0
  - send2trash=1.5.0
  - setuptools=49.6.0
  - shapely=1.7.1
  - simplejson=3.17.2
  - sip=4.19.24
  - six=1.15.0
  - snappy=1.1.8
  - snowballstemmer=2.1.0
  - snuggs=1.4.7
  - sortedcontainers=2.4.0
  - sphinx=4.3.0
  - sphinxcontrib-applehelp=1.0.2
  - sphinxcontrib-devhelp=1.0.2
  - sphinxcontrib-htmlhelp=2.0.0
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=1.0.3
  - sphinxcontrib-serializinghtml=1.1.5
  - spyder=5.0.2
  - spyder-kernels=2.0.5
  - sqlite=3.34.0
  - statsmodels=0.12.1
  - terminado=0.9.1
  - testpath=0.4.4
  - text-unidecode=1.3
  - textdistance=4.2.2
  - threadpoolctl=2.1.0
  - three-merge=0.1.1
  - tifffile=2020.12.8
  - tiledb=2.1.3
  - tinycss2=1.1.0
  - tk=8.6.10
  - toml=0.10.2
  - tomli=1.2.2
  - toolz=0.11.1
  - tornado=6.1
  - tqdm=4.62.3
  - traitlets=5.0.5
  - typed-ast=1.5.0
  - typing-extensions=3.7.4.3
  - typing_extensions=3.7.4.3
  - ujson=4.2.0
  - unidecode=1.3.2
  - uritemplate=3.0.1
  - urllib3=1.25.11
  - vc=14.1
  - vs2015_runtime=14.16.27012
  - watchdog=1.0.2
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.36.1
  - win_inet_pton=1.1.0
  - wincertstore=0.2
  - winpty=0.4.3
  - wrapt=1.11.2
  - xerces-c=3.2.3
  - xz=5.2.5
  - yaml=0.2.5
  - yapf=0.31.0
  - yarl=1.6.3
  - zeromq=4.3.3
  - zfp=0.5.5
  - zipp=3.4.0
  - zlib=1.2.11
  - zstd=1.4.5
  - pip:
    - cfgv==3.3.1
    - cykhash==1.0.2
    - cython==0.29.21
    - descartes==1.1.0
    - distlib==0.3.4
    - docutils==0.16
    - filelock==3.4.2
    - identify==2.4.5
    - nodeenv==1.6.0
    - osmnx==0.16.2
    - platformdirs==2.4.1
    - pre-commit==2.17.0
    - pygeos==0.8
    - pyrobuf==0.9.3
    - pyrosm==0.6.0
    - python-rapidjson==0.9.4
    - sphinx-rtd-theme==1.0.0
    - sphinx-tabs==3.2.0
    - virtualenv==20.13.0
